name: client
description: Client part for aerohockey

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  browser: '>=0.10.0 <0.11.0'
  js: "^0.6.0"
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
  - dart_to_js_script_rewriter
  - $dart2js:
      sourceMaps: true