name: server
description: Server part for aerohockey

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  shelf: any
  shelf_bind: any
  shelf_rest: any
  logging: any
  shared:
    path: ../shared

dev_dependencies:
  test: '0.12.28'