name: shared
description: Shared part for aerohockey

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  uuid: any
  generators:
    path: ../generators

dev_dependencies:
  test: '0.12.24'
  source_gen: any
  build_runner: 0.5.0
